ARDUINO_DIR = /usr/share/arduino

TARGET = servo
BOARD_TAG = uno
ARDUINO_PORT= /dev/ttyACM0

#ARDUINO_LIBS = WIRE
#ARDUINO_LIBS += DS3231

ARDUINO_DIR = /usr/share/arduino
AVR_TOOLS_PATH = /usr/bin

include /usr/share/arduino/Arduino.mk
